### ISSUE TITLE
Transform type entities into type fields

### ISSUE THREAD

**Issue by ferschke** [DiscourseDB/discoursedb-model#13]
Most DiscourseDB entities are typed, i.e. they have a relation to a *Type entity - e.g. Contribution - ContributionType.

Currently, Type entities merely contain a String value and a Set of entities that belong to the type.
The range of values is limited by the API, not the DB.
Consequently, we could achieve the same by flattening the hierarchy and directly including the type value in the typed entity.
This would get rid of a  lot of complexity, simplify both the API and queries and have the same functionality. I propose to transform type definitions from relations to type entities to type String values.

Before doing so, it should be discussed whether to stick with purely API-level enums or whether we want to introduce DB-level enums to limit the range of type values. This discussion started at the hack day, but didn't come to a clear conclusion.

**Comment by cbogart** [comment]
I think it's inconvenient to have to change the discoursedb-model project every time I add a new type to discoursedb-github, although I admit it does force me to think carefully about where I can and should follow the conventions set by the other converters.

I would definitely support the change, but maybe we should in some other document maintain a canonical list of the type strings we use, with descriptions of how the various converters use them, so we can try to stay consistent across projects.

**Comment by ferschke** [comment]
Changing types to be represented as simple String values rather than links to type entities does not change the way the overall model works. We can still have API-level enums to register the possible type values. It would simply get rid of the Type entities.

Independent from that, we could register the possible types as DB-level enums. That happens in the Entity classes which would expose the possible values for types in the API. However, it might be inconvenient if we have to change the model for every new type.

So, from what I understand, you would support moving to simple type String values rather than type entities, but keep the API-Level enums to define the value ranges?

**Comment by cbogart** [comment]
Ah, I see.

I do support moving to simple String values.  But as for the API I'd kind of rather just use plain old strings directly in the API calls and leave it up to the converter to define constants for them. Maybe the API could have set of "common" constants for strings, and each converter could additionally provide custom ones for when the common ones don't make sense.  It seems likely that there will be some github-specific types that needn't be put in a common enum for everybody, and that'll be true of other new applications of DiscourseDB.

But, I don't feel strongly about that -- could be that forcing us all to keep our constants in a common place for the time being will encourage consistency, and we could relax that constraint later when we start to understand what should be common/standard and what will only be useful for individual applications.

**Comment by ferschke** [comment]
Type entities have been transformed into String values. The Service classes have the same signatures as before and accept the API-level enums
