### ISSUE TITLE
Generalize "context" to "contribution"

### ISSUE THREAD

**Issue by ferschke** [DiscourseDB/discoursedb-model#14]
Context entities currently have a special status, but hardly behave differently than Contribution entities.
Contributions and Content entities each have related Content entities for versioning purposes. 
A Contribution can have a relation to at most one Context. Apart from this, the two entities are identical.
It is difficult to represent cases where a discussion is a context of another discussion, which might happen on some platforms.
To simplify the schema, make it more flexible and support the above mentioned use cases, we should remove Context entities and use Contributions to represent context information.
This would require a new "context relation" between two Contribution entities.
The types currently assigned to Context entities can be carried over to Contribution entities.

In my opinion, this won't cause additional problems, but solve some of the current shortcomings.
The only minor downside is the naming convention - a Wikipedia Article, for example, which is the context of a discussion would be represented as a "Contribution". While the modelling is appropriate, the naming of this entity might not be the best choice.

**Comment by cbogart** [comment]
:+1: I think it's likely this will be useful in discoursedb_io_github as well
