### ISSUE TITLE
Represent contexts based on spans or multiple documents.

### ISSUE THREAD

**Issue by ferschke** [DiscourseDB/discoursedb-model#15]
The classroom salon data introduced a new requirement.
Rather than having a whole "document" as the context (or prompt) of a discussion, threads are tied to a span or region in a document. Currently, we can only attach whole documents as a context. 

With the changes proposed in issue #14, Context might be represented as Contribution entities using a context relation. This relation might carry information about the point of reference - e.g. just a span of the document represented by the context-contribution. To achieve this, we also have to add relations to a particular content entity, since spans would refer to the text or data field in that table.

The inverse issue of having a span of a document as a context arises in projects such as GitHub, where multiple documents might represent the context of a discussion.
Consequently, the context relation suggested in Issue #14 should be able to refer to multiple contributions.

**Comment by cbogart** [comment]
Paraphrasing to see if I understand: does this mean that a ContextRelation would have:
  * A source Contribution
  * A list of targets, each consisting of:
     * A target Contribution
     * The particular Content item associated with the Contribution
     * The start and end character positions within the Content

**Comment by ferschke** [comment]
exactly, that's what I was thinking
